# service configuration for our dockerized Rails app
app:
  # use the Dockerfile next to this file
  build: .

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV

  # makes the app container aware of the DB container
  links:
    - db

  # expose the port we configured Unicorn to bind to
  ports:
    - "3000:3000"

# service configuration for our database
db:

  # use the preferred version of the official MongoDB image
  # see https://hub.docker.com/_/mongo
  image: mongo:3.2.10

  # # persist the database between containers by storing it in a volume
  # volumes:
  #   - docker-example-postgres:/var/lib/postgresql/
